### ISSUE TITLE
fwd changes catch.wt

### ISSUE THREAD

**Issue by hgerritsen** [flr/FLasher#65]
the catch weights for the years for which the forecast is performed in fwd() are changed from the input stock object. In the ple4 example the difference is small but for other stocks it can be considerable. Why would it do that?
The following code was run on Flasher 0.6.5 in R version 4.0.2

`library(FLCore)
library(FLasher)

data(ple4)
ple4_mtf <- stf(ple4, nyears = 3)
ple4_sr <- fmle(as.FLSR(ple4, model="bevholt"), control=list(trace=0))
f_status_quo <- mean(fbar(ple4)[,as.character(2015:2017)])
ctrl_target <- data.frame(year = 2018:2020,
                                quant = "f",
                                value = f_status_quo)
ctrl_f <- fwdControl(ctrl_target)
ple4_f_sq <- fwd(ple4_mtf, control = ctrl_f, sr = ple4_sr)
ple4_mtf@catch.wt[,ac(2018:2020)]/ple4_f_sq@catch.wt[,ac(2018:2020)]
`

the catch weights in ple_mtf are not identical to ple4_f_sq.

**Comment by iagomosqueira** [comment]
There was indeed a bug in the method recalculating `catch.wt` in flr/FLFishery. This is now fixed in https://github.com/flr/FLFishery/commit/86aeb15ed437c1b457a1721485c85a1c962ce4e6.

An FLStock is converted inside `fwd()` to an FLBiol and an FLFishery, as those are the classes used internally. Catch numbers and weights are stored inside an `FLCatch` object, which only has slots for landings and discards. So after the projection, `catch.wt` in `FLStock` for the projected years is reconstructed from `landings.n` and `wt`, and `discards.n` and `wt`. This leads to some small discrepancies, but the result is now this

```
> ple4_mtf@catch.wt[,ac(2017:2020)]/ple4_f_sq@catch.wt[,ac(2017:2020)]
An object of class "FLQuant"
, , unit = unique, season = all, area = unique
    year
age  2017    2018    2019    2020
  1  1.00000 1.00022 1.00022 1.00022
  2  1.00000 0.99973 0.99973 0.99973
  3  1.00000 1.00030 1.00030 1.00030
  4  1.00000 0.99980 0.99980 0.99980
[...]
```
A new release of FLFishery will be made to the repository soon.

**Comment by hgerritsen** [comment]
Thanks!

**Comment by iagomosqueira** [comment]
Thanks for spotting it

**Comment by hgerritsen** [comment]
It was actually a very useful bug because it made me realise that the landings and discards did not add up to the catch in the stock I was working on.
Hans
